/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AskCoachRouteImport } from './routes/ask-coach'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as MeRouteImport } from './routes/me'
import { Route as SendCallupRouteImport } from './routes/send-callup'
import { Route as ApiAskCoachRouteImport } from './routes/api/ask-coach'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AskCoachRoute = AskCoachRouteImport.update({
  id: '/ask-coach',
  path: '/ask-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const SendCallupRoute = SendCallupRouteImport.update({
  id: '/send-callup',
  path: '/send-callup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskCoachRoute = ApiAskCoachRouteImport.update({
  id: '/api/ask-coach',
  path: '/api/ask-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/approvals': typeof ApprovalsRoute
  '/ask-coach': typeof AskCoachRoute
  '/desk': typeof DeskRoute
  '/me': typeof MeRoute
  '/send-callup': typeof SendCallupRoute
  '/api/ask-coach': typeof ApiAskCoachRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/approvals': typeof ApprovalsRoute
  '/ask-coach': typeof AskCoachRoute
  '/desk': typeof DeskRoute
  '/me': typeof MeRoute
  '/send-callup': typeof SendCallupRoute
  '/api/ask-coach': typeof ApiAskCoachRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/approvals': typeof ApprovalsRoute
  '/ask-coach': typeof AskCoachRoute
  '/desk': typeof DeskRoute
  '/me': typeof MeRoute
  '/send-callup': typeof SendCallupRoute
  '/api/ask-coach': typeof ApiAskCoachRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/approvals'
    | '/ask-coach'
    | '/desk'
    | '/me'
    | '/send-callup'
    | '/api/ask-coach'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/approvals'
    | '/ask-coach'
    | '/desk'
    | '/me'
    | '/send-callup'
    | '/api/ask-coach'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/approvals'
    | '/ask-coach'
    | '/desk'
    | '/me'
    | '/send-callup'
    | '/api/ask-coach'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AskCoachRoute: typeof AskCoachRoute
  DeskRoute: typeof DeskRoute
  MeRoute: typeof MeRoute
  SendCallupRoute: typeof SendCallupRoute
  ApiAskCoachRoute: typeof ApiAskCoachRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-coach': {
      id: '/ask-coach'
      path: '/ask-coach'
      fullPath: '/ask-coach'
      preLoaderRoute: typeof AskCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-callup': {
      id: '/send-callup'
      path: '/send-callup'
      fullPath: '/send-callup'
      preLoaderRoute: typeof SendCallupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask-coach': {
      id: '/api/ask-coach'
      path: '/api/ask-coach'
      fullPath: '/api/ask-coach'
      preLoaderRoute: typeof ApiAskCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  ApprovalsRoute: ApprovalsRoute,
  AskCoachRoute: AskCoachRoute,
  DeskRoute: DeskRoute,
  MeRoute: MeRoute,
  SendCallupRoute: SendCallupRoute,
  ApiAskCoachRoute: ApiAskCoachRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
