/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskCoachRouteImport } from './routes/ask-coach'
import { Route as SendCallupRouteImport } from './routes/send-callup'
import { Route as ApiAskCoachRouteImport } from './routes/api/ask-coach'
import { Route as ApiDeskRouteImport } from './routes/api/desk'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskCoachRoute = AskCoachRouteImport.update({
  id: '/ask-coach',
  path: '/ask-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const SendCallupRoute = SendCallupRouteImport.update({
  id: '/send-callup',
  path: '/send-callup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskCoachRoute = ApiAskCoachRouteImport.update({
  id: '/api/ask-coach',
  path: '/api/ask-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskRoute = ApiDeskRouteImport.update({
  id: '/api/desk',
  path: '/api/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask-coach': typeof AskCoachRoute
  '/send-callup': typeof SendCallupRoute
  '/api/ask-coach': typeof ApiAskCoachRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask-coach': typeof AskCoachRoute
  '/send-callup': typeof SendCallupRoute
  '/api/ask-coach': typeof ApiAskCoachRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask-coach': typeof AskCoachRoute
  '/send-callup': typeof SendCallupRoute
  '/api/ask-coach': typeof ApiAskCoachRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask-coach'
    | '/send-callup'
    | '/api/ask-coach'
    | '/api/desk'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask-coach'
    | '/send-callup'
    | '/api/ask-coach'
    | '/api/desk'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/ask-coach'
    | '/send-callup'
    | '/api/ask-coach'
    | '/api/desk'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskCoachRoute: typeof AskCoachRoute
  SendCallupRoute: typeof SendCallupRoute
  ApiAskCoachRoute: typeof ApiAskCoachRoute
  ApiDeskRoute: typeof ApiDeskRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-coach': {
      id: '/ask-coach'
      path: '/ask-coach'
      fullPath: '/ask-coach'
      preLoaderRoute: typeof AskCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-callup': {
      id: '/send-callup'
      path: '/send-callup'
      fullPath: '/send-callup'
      preLoaderRoute: typeof SendCallupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask-coach': {
      id: '/api/ask-coach'
      path: '/api/ask-coach'
      fullPath: '/api/ask-coach'
      preLoaderRoute: typeof ApiAskCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk': {
      id: '/api/desk'
      path: '/api/desk'
      fullPath: '/api/desk'
      preLoaderRoute: typeof ApiDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskCoachRoute: AskCoachRoute,
  SendCallupRoute: SendCallupRoute,
  ApiAskCoachRoute: ApiAskCoachRoute,
  ApiDeskRoute: ApiDeskRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
